# SimpleChores Schedule to Todo Automation Blueprint
blueprint:
  name: SimpleChores – Schedule → To-do
  description: Create chores when a Schedule helper turns on.
  domain: automation
  input:
    schedule_entity:
      name: Schedule
      selector: { entity: { domain: schedule } }
    kid_todo:
      name: Kid To-do entity
      selector: { entity: { domain: todo } }
    chores:
      name: Chores (list of {summary, points})
      default:
        - { summary: "Tidy room (+5)", points: 5 }
        - { summary: "Set table (+2)", points: 2 }

trigger:
  - platform: state
    entity_id: !input schedule_entity
    from: "off"
    to: "on"

action:
  - repeat:
      for_each: !input chores
      sequence:
        - service: todo.add_item
          data:
            entity_id: !input kid_todo
            item:
              summary: "{{ repeat.item.summary }}"
