# SimpleChores Schedule to Todo Automation Blueprint
blueprint:
  name: SimpleChores – Schedule → To-do
  description: Create chores when a Schedule helper turns on using SimpleChores integration.
  domain: automation
  input:
    schedule_entity:
      name: Schedule
      selector: { entity: { domain: schedule } }
    kid:
      name: Kid ID
      selector: { text: {} }
    chores:
      name: Chores (list of {title, points})
      default:
        - { title: "Tidy room", points: 5 }
        - { title: "Set table", points: 2 }

trigger:
  - platform: state
    entity_id: !input schedule_entity
    from: "off"
    to: "on"

action:
  - repeat:
      for_each: !input chores
      sequence:
        - service: simplechores.create_adhoc_chore
          data:
            kid: !input kid
            title: "{{ repeat.item.title }}"
            points: "{{ repeat.item.points }}"
